lane :update_project_with_build_number do

  ensure_git_status_clean

  build = reserve_git_build_number(
    tag_prefix: 'build/'
  )

  increment_build_number(
    build_number: build
  )
  
  clean_build_artifacts
  reset_git_repo(skip_clean: true)

end

lane :show_build_number do

  build = get_git_build_number(
    tag_prefix: 'build/'
  )

  puts "Current build number: #{build}"

end
